name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iOS:
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.1", "12.5.1", "12.4"]
        include:
          - xcode: "13.1"
            macos: macOS-11
          - xcode: "12.5.1"
            macos: macOS-11
          - xcode: "12.4"
            macos: macOS-11
    runs-on: ${{ matrix.macos }}

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
